import type { BaseColor, TokenColor, UIColor } from "../type";
import { brighten, parseColor } from "../util";
import type { Colors } from ".";

const blue = {
  50: "#f8fafc",
  100: "#f1f5f9",
  200: "#e2e8f0",
  300: "#cbd5e1",
  400: "#94a3b8",
  500: "#64748b",
  600: "#475569",
  700: "#334155",
  800: "#1e293b",
  900: "#0f172a",
  950: "#020617",
};

export const base: BaseColor = {
  gray: parseColor("hsl(0, 0%, 50%)"),
  red: parseColor("hsl(0, 100%, 76%)"),
  orange: parseColor("hsl(20, 80%, 72%)"),
  yellow: parseColor("hsl(36, 78%, 78%)"),
  lightYellow: parseColor("hsl(28, 32%, 84%)"),
  lightGreen: parseColor("hsl(76, 72%, 70%)"),
  green: parseColor("hsl(130, 35%, 65%)"),
  cyan: parseColor("hsl(180, 52%, 75%)"),
  sky: parseColor("hsl(212, 85%, 87%)"),
  blue: parseColor("hsl(210, 100%, 72%)"),
  purple: parseColor("hsl(247, 100%, 82%)"),
  pink: parseColor("hsl(328, 70%, 78%)"),
  desaturatedOrange: "#CE9178",
  lightOrange: "#ff9f79",
  cyanBlue: "#569cd6",
  lightCyan: "#9cdcfe",
  lavenderMagenta: "#ff84f5",
  greenCyan: "#57f8d8",
  greenShade: "#74d349",
  crow: "#0D0907",
  void: "#010207",
};

export const uiColor: UIColor = {
  activeBackground: "#000000",
  activeForeground: "#00fffb",
  activityBarForeground: "#ffcc00",
  activityBarInactiveForeground: "#676166",
  buttonBackground: "#12122c",
  buttonHoverBackground: "#2b2b5a",
  elementBorder: "#999999",
  foreground: "#ffffff",
  foregroundAlt: "#000000cc",
  background: "#000000",
  backgroundAlt: "#ff0000",
  backgroundEditor: "#000000ff",
  backgroundEditorAlt: "#000033",
  badgeBackground: "#222222",
  badgeForeground: "#ffffff",
  border: "#35426b",
  borderAlt: "#676166",
  borderActive: "#00fffb",
  borderNormal: "#00fffb",
  defaultBlack: "#000000",
  dropBackground: "#2b2b5acc",
  highlightBg: "#e9ba0083",
  hoverBackground: "#000033",
  inactiveBackground: "#000000",
  inactiveForeground: "#cccccc",
  lineHighlight: "#1c1c1c",
  primary: parseColor("hsl(210, 28%, 52%)"),
  secondary: "#2b2b5a",
  cursor: "#5f3b23",
  selection: "#ffffff33",
  scrollbar: brighten(blue[700], 4),
  listItem: "#111111",
  listItemForeground: "#00fffb",
  listItemHoverBackground: "#2c145f7a",
  panelBorder: "#ff0000",
  rangeBackground: "#3a3a3a",
  rangeBorder: blue[700],
  toolbarBackground: "#191936",
  toolbarBorder: "#191936",
  wordHighlight: "#575757",
};

export const tokenColor: TokenColor = {
  htmlTag: base.red,
  comment: base.greenShade,
  string: base.desaturatedOrange,
  keyword: base.purple,
  keywordAlt: base.lavenderMagenta,
  number: base.lightGreen,
  boolean: base.purple,
  operator: base.sky,
  function: base.yellow,
  property: {
    normal: base.lightCyan,
    declaration: base.lightCyan,
    defaultLib: base.lightGreen,
  },
  parameter: base.yellow,
  variable: {
    local: base.yellow,
    defaultLib: base.pink,
  },
  constant: base.orange,
  enum: base.orange,
  class: base.greenCyan,
  interface: {
    normal: base.orange,
    defaultLib: base.orange,
  },
  type: {
    normal: base.greenCyan,
    parameter: base.yellow,
    primitive: base.greenCyan,
    defaultLib: base.lightGreen,
  },
  builtin: base.purple,
  namespace: base.pink,
  punctuation: base.sky,
  error: base.red,
  escape: base.blue,
  link: base.blue,
  regex: base.green,
  js: {
    component: base.cyan,
    templateExpression: base.cyan,
  },
  css: {
    variable: base.cyan,
    unit: base.blue,
    function: base.purple,
    pseudo: base.blue,
  },
  java: {
    class: base.orange,
    import: base.yellow,
    annotation: base.blue,
  },
  python: {
    fstring: base.cyan,
  },
  markdown: {
    title: base.purple,
    bold: base.orange,
    italic: base.orange,
    quotes: base.cyan,
    code: base.red,
  },
  diff: {
    deleted: base.red,
    inserted: base.green,
    changed: base.yellow,
    header: base.blue,
    range: base.purple,
  },
};

const colors: Colors = {
  baseColor: base,
  tokenColor,
  uiColor,
  theme: "dark",
};
export default colors;
